### ISSUE TITLE
I miss my contextual Cut/Copy/Paste in Electon!

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#10]
I see that most browsers allow this now:

http://stackoverflow.com/questions/22581345/click-button-copy-to-clipboard-using-jquery

I know this may need more than one solution but we need to do something. 

Consider:
`<gs-rightclick>
    <template></template>
</gs-rightclick>
`
Advantages: 
    would be very easy to add a contextual menu to an element or a part of a page.

Disadvantages:
    May not work well with elements that are heavily styled or located.
    May not work well with dynamic elements or templates.
    May not work with Ace editor.

A function that sets up a contextual menu for a whole page may work well but would work everywhere the same. I can foresee many situations where this is less than ideal, eg. Postage.

Another thing to think about is maybe adding an attribute to individual elements. Consider where "rcm" stands for "right click menu":
`<div class="ace-container" rcm="ace-rtclick-menu">`
    then elsewhere: `<template id="ace-rtclick-menu">`

or 

```
<gs-envelope ...>
    ....
        <tr ...>
            <th rcm="env-rtclick-menu">
```

```
then elsewhere: `<template id="env-rtclick-menu">`
```

Either of these would give excellent control, however, I can't imagine a way to code an Ace container to pull the selected text while causing the TH element to give you the expected tab delimited values of the entire record.

I'm sure there exist many other potential implementations. I just want to get things started right now.

**Comment by nunziotocci** [comment]
This is actually something that is done inside electron.
[There is a project](https://github.com/sindresorhus/electron-context-menu) that adds cut/copy/paste into a context menu for electron.

I will look into this.

**Comment by justintocci** [comment]
Fair enough. 

Truth be told, I haven't needed a contextual menu yet in Envelope. It just seemed like a web-only solution would be cleaner and give us more options. But if there is something we can quickly use to solve the Electron issue and the license is ok, then I'm happy to put off an Envelope solution for custom menus until there is demand from users.
