### ISSUE TITLE
Firefox error with GS.findParentElement function

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#112]
Firefox will give the error below if `GS.findParentElement(elementToCheckFrom, selectorToFind)` is called with the `document` as the element to check from.

`
TypeError: 'mozMatchesSelector' called on an object that does not implement interface Element.
`

This is because the x-tag API function `xtag.matchSelector` tries to call `mozMatchesSelector` on the `document` in Firefox. According to the [Firefox documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Read-only) (the link was provided with the error in the console) this error occurs because `mozMatchesSelector` is trying to write to an non-writable property. In strict mode for Firefox, writing to an non-writable property causes an error.

To fix this, we need all instances of `xtag.matchSelector` to be protected from the `document` variable.

**Comment by michaeltocci** [comment]
While we're in there, we might as well protect it from `window` the same way.

**Comment by crosstocci** [comment]
Fixed in next release.
