### ISSUE TITLE
GS-Table Not Reverting

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/envelope#118]
010-table.js
Lines
10337
10370
10424
10429

Currently the GS-Table does not revert, the reason being if it reverts then all the text you typed in the field is gone. However now that it doesn't when you hit a checkbox you have to refresh to see the reverted changes.

Maybe we should make the record red when an update fails? Perhaps have a revert button next to the record so that you can copy out the data before you revert?

We need to get together with Jen, (she brought up the issue) and figure out how it should behave.

**Comment by crosstocci** [comment]
Spoke to Jen. It is now fixed in the next release.
