### ISSUE TITLE
File Search Screen on MSSQL Server

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#12]
When searching for a file, clicking on any of the links to go to a match opens the File Editor, but the file editor errors.

I found out that the link that File Search sends to the File Editor is missing the slash after "/app".

**Comment by nunziotocci** [comment]
Fixed in commit [7c505ab8141761a3a0f6342fc7276482254572a9](https://github.com/workflowproducts/envelope/commit/7c505ab8141761a3a0f6342fc7276482254572a9)
