### ISSUE TITLE
Timekeeping problem

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#120]
When I make an adjustment to a note and click on another field, the focus goes away.

I have to do it quickly to make it break, so I assume this is about the save record process.

**Comment by nunziotocci** [comment]
I can't replicate this, it may have been fixed already. Let me know if it's still broken.

**Comment by michaeltocci** [comment]
Focus into one section of a gs-time, make a change and then focus into another section of another gs-time.

**Comment by nunziotocci** [comment]
> Focus into one section of a gs-time, make a change and then focus into another section of another gs-time.

Fixed in the next release.
