### ISSUE TITLE
File Manager Should Have a "Select All" Button

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#121]
The File Manager should have a "Check All" button. It should be an icon-only button at the top-right. All it will do is check the checkboxes for all files and folders in the current directory.

**Comment by justintocci** [comment]
convention would want it to be labeled "Select all"

that's what i always see


Regards,

Justin Tocci
Programmer
Workflow Products, LLC
workflowproducts.com <http://www.workflowproducts.com/>
609 W Harwood Road
Hurst, TX 76054
817-503-9545

**Comment by michaeltocci** [comment]
Sounds good. We'll do "Select All" instead of "Check All".

**Comment by crosstocci** [comment]
Added in next release.
