### ISSUE TITLE
File Manager needs a redesign

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#123]
I have a folder with 25k items in it and the file manager javascript crashes.

I think we need to re-design the file manager so it can benefit from the optimization for large lists that was put into gs-table. I'd be happy to just use gs-table but if it's easier to start with that and modify it I'm ok with that too.

**Comment by crosstocci** [comment]
I have tested the new file manager with 25k files, it does not crash, but takes a moment to display. I have added a loader to display when loading a file list.
