### ISSUE TITLE
Add User Option On Paste To GS-Table

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#125]
When Nunzio is finished creating the COPY INSERT API, add a popup asking the user if they would prefer a COPY-based paste or an INSERT-based paste. This is a developer option, so an automatic popup should be turned on by an attribute.

Make sure to say that COPY-based paste is faster, but does not allow triggers to fire.

**Comment by crosstocci** [comment]
Postage already handles COPY statements. Closing.
