### ISSUE TITLE
GS-Table Crashes Page After Large INSERT

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#126]
The INSERT completes, but the page crashes.

The data was 5108 lines in a single column with an average 200 character length.

**Comment by justintocci** [comment]
Actually, this only happens if the console is open.

**Comment by crosstocci** [comment]
I've removed what I think was the problem: A console.log that logs the inserted data, in your case many thousands of characters of inserted data.

I inserted 40,000 rows with a single column containing 1000 characters, it works properly with the console open.
