### ISSUE TITLE
File Search Confusing Match Number

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#13]
When I search for something the File Search gives a confusing match number, example below.

![issue](https://cloud.githubusercontent.com/assets/10438221/19492110/02ed3c8e-953b-11e6-9141-f78083d138ab.png)

This search found 2 files with a total of 3 occurrences between them, but the File Search screen says "3 Matches". What File Search should say is "2 Files, 3 Occurrences".

**Comment by josephtocci** [comment]
Fixed in commit 2f1d018e72ce8847f89a6f013cc650d15985178f
