### ISSUE TITLE
Detect High CPU usage

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/envelope#132]
Specifically on Windows, we encountered an issue where the Envelope Process stopped accepting connections and was stuck at 100% CPU usage.

In the service we should periodically check the CPU usage and get a memory dump for examination.

You can manually get a memory dump [like so](https://superuser.com/a/146780), but it should be possible to do this from C.

**Comment by justintocci** [comment]
the interval for checking should be user configurable. no config or zero should be don't check.

**Comment by crosstocci** [comment]
Covered by other initiatives.
