### ISSUE TITLE
gs-envelope sort buttons

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/envelope#133]
On GS-Envelope there is a button at the bottom left for a list of columns that it is sorted by. When I go to add one, I click on the column I want and nothing seemed to happen. It did not drop off the list or show that I clicked on it. So I clicked on it multiple times and when I closes it, it showed that it was now sorted by that same column multiple times. When you add a column to sort it should drop off the list of available columns to sort.

**Comment by crosstocci** [comment]
Fixed in next release.
