### ISSUE TITLE
Collaborative editing

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/envelope#135]
It could be useful to have multiple people editing the same file.

Thoughts?

**Comment by justintocci** [comment]
My first thought is it isn't that difficult to implement. My second is it is most certainly of dubious use.

I've only ever done this a few times and it never really mattered. Sharing screens with VNC, Hangouts or other tools works much better for virtually all things in our business.

**Comment by michaeltocci** [comment]
Agreed.

Another problem is that if two people are editing, you have to wait for the other guy to finish before you can test.

**Comment by nunziotocci** [comment]
> My first thought is it isn't that difficult to implement My second is it is most certainly of dubious use.

Thinking about this, I think the real reason to implement the API isn't necessarily for the collaboration, but it would make file editing requests much smaller and would reduce network load.

> Another problem is that if two people are editing, you have to wait for the other guy to finish before you can test.

Also, I think the only real use would be for writing copy on the same page. But, on the other hand I don't expect many people would be writing copy in our file editor.

**Comment by crosstocci** [comment]
This doesn't seem necessary. If you need to work with someone offsite a VNC is a great option.
