### ISSUE TITLE
GS-Table Arrow Key Text Selection

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#138]
Right now, if you want to select all the text in a cell with arrow keys (assuming the cursor is in the text already), you have to use `shift`+`right arrow` to go to the end.

Standard practice is to use `shift`+`down arrow` to skip all the way to the end. Right now, that doesn't work. It just changes from text selection to cell selection.

**Comment by nunziotocci** [comment]
The same problem seems to be present with `shift`+`end` and `shift`+`home`. If the cursor is in the input it shouldn't override any selection keys.

**Comment by michaeltocci** [comment]
Maybe we should be even more dynamic. For example: if you do `shift`+`down arrow` while at the last character already, then in breaks into cell selection. So, if the text selection goes outside the bounds of the full text, it moves to cell selection.

We've done this before, we would just have to dig up the code and adapt it.

That way, if the user clicks into a field and they want to do cell selection, they can intuitively arrow out of the text.

**Comment by crosstocci** [comment]
Fixed in next release.
