### ISSUE TITLE
GS-Form multiple updates

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/envelope#140]
When making two changes in a GS-Form in quick succession, then an error occurs on the second change. Make it so that the GS-Form queues updates.

**Comment by josephtocci** [comment]
If two updates are made in quick succession, the second one fails. This is not just with the GS-Form, instead it should be all four requests: `SELECT` `INSERT` `UPDATE` `DELETE`. Create a Queue for these types of requests and update all of the widgets.

**Comment by crosstocci** [comment]
Most requests don't need to be queued.
INSERT and DELETE will not error if you request multiple at once.
SELECT is an inconvience when refreshing like that, but once a select begins returning it cannot be cancelled and the next one already waits for the first to finish.

I have added a warning to the record elements when you attempt to select while a select is happening. This should help developers prevent that behaviour.

I also added the UPDATE queue as requested to the record elements.
