### ISSUE TITLE
Collected notes/issues #2

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#158]
GS-GRID: if the min-widths attribute sets a column width to "0", hide that column at that width.

WEBSOCKETS: Brave Browser limits each domain to ten websockets between all pages. We should have some kind of warning to make sure the developer is adequately warned.

GS-COMBO: On Android, selecting an option doesn't change the value.

GS-COMBO: Unsure how to reproduce the issue, but on occasion ends up in a loop and reaches maximum call stack size. This doesn't seem to interrupt function.

FILE EDITOR: We should have a snippet (or a utility CSS class) for allowing background colors to be shown when printing the webpage.
```
    -moz-print-color-adjust: exact;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
```

**Comment by crosstocci** [comment]
GS-GRID: if the min-widths attribute sets a column width to "0", hide that column at that width.
Added/fixed "small" keyword being replaced by "all"

WEBSOCKETS: Brave Browser limits each domain to ten websockets between all pages. We should have some kind of warning to make sure the developer is adequately warned.
Added warning when on brave or when more than nine websockets are opened.

GS-COMBO: On Android, selecting an option doesn't change the value.
Couldn't reproduce, Combo would not open in gs-table on android but has been fixed.

GS-COMBO: Unsure how to reproduce the issue, but on occasion ends up in a loop and reaches maximum call stack size. This doesn't seem to interrupt function.
Fixed. AttributeChanged was calling renderControl when the value attribute was changed. renderControl set the value attribute. This made a loop. Now render control only sets value attribute if the value is different.

FILE EDITOR: We should have a snippet (or a utility CSS class) for allowing background colors to be shown when printing the webpage.
Added.
