### ISSUE TITLE
GS-Table on iOS

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#159]
On some applications on iOS (see our TEMP internal app for an example), focusing a field causes the keyboard to pop up (taking vertical space), which causes the page to shrink, which causes the focused field to be hidden, which causes the field to become unrendered, which causes the field to lose focus, which causes the keyboard to close. Preventing the field from being updated.

**Comment by crosstocci** [comment]
This seems to be resolved.

IOS now keeps the page full height and simply scrolls to the focused element. No resizing takes place.

It would be smart to consider this when writing Issue #144
