### ISSUE TITLE
Access-Control-Allow-Origin: *

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/envelope#18]
We need to add a config variable to allow other sites to send an auth request and get a cookie for the destination site. All it would do is add the Access-Control-Allow-Origin header to the /env/auth response.

**Comment by josephtocci** [comment]
This issue was posted before nocookie, there is no need to add this to auth.

Accept allows you to set Access-Control-Allow-Origin yourself, I just have to add the configuration variable to set it in the actionnc responses.

**Comment by josephtocci** [comment]
Added, will be seen in the next release.
