### ISSUE TITLE
fedora24 linux install issues - unnecessary dependancies

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#2]
there were several dependencies missing for fedora24 linux which were not documented and not found by your 'configure' script.

I had to run it another two times to find all the missing packages and install these:

libtool 
 autoconf-2.69-22.fc24.noarch    A GNU tool for automatically configuring source code
 automake-1.15-6.fc24.noarch    A GNU tool for automatically creating Makefiles
 libtool-2.4.6-11.fc24.x86_64    The GNU Portable Library Tool
 perl-Thread-Queue-3.11-1.fc24.noarch    Thread-safe queues

autopoint
gettext-common-devel-0.19.8.1-2.fc24.noarch    Common development files for gettext
gettext-devel-0.19.8.1-2.fc24.x86_64    Development files for gettext

cvs
###### 

We need to remove the need for these dependancies.

First, fix configure/make process so that we can compile on all operating systems without these. 
Then we need to add binary install packages for most operating systems to the releases. this way most people won't even need to compile.

**Comment by nunziotocci** [comment]
The issue on fedora is resolved, but we will leave this open until we have done compile/install testing on mac for the same issues.

**Comment by nunziotocci** [comment]
I have tested on fresh OSX, and this issue is now fixed
