### ISSUE TITLE
Template Element on Edge does not work

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/envelope#22]
This causes issues with the widgets.

![capture](https://cloud.githubusercontent.com/assets/7560749/20402907/3b104124-acc4-11e6-9173-ffcbcd0471e9.PNG)

**Comment by nunziotocci** [comment]
My edge version information:

![capture](https://cloud.githubusercontent.com/assets/7560749/20402999/a6fef678-acc4-11e6-9820-423e379707ac.PNG)

**Comment by michaeltocci** [comment]
I've tested on MS Edge and the issue is that Edge doesn't give the `children` property for `yourTemplateElement.content`. I've used the `children` property this way a few times in the UI.

I'll close the issue after I fix the instances where this is broken.

**Comment by michaeltocci** [comment]
I've updated the code that is incorrect, could you explain specifically what issues you were having so that I can test them?

**Comment by nunziotocci** [comment]
I looked around, everything seems fine. I will close this issue for now.

PS: It now says FUNCTION PASS:
![capture3](https://cloud.githubusercontent.com/assets/7560749/21118336/0b1f49c4-c083-11e6-8efe-f0f8fe14629f.PNG)
