### ISSUE TITLE
Update is slow on complex views

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/envelope#23]
In some cases if you have a complex view that returns quickly, it will still be extremely slow to update (~40s). We have a way to fix it and are working on it.

We've traced it to a possible query plan bug, when envelope runs this query:
```
SELECT count(*),
        SUM(CASE WHEN md5(change_stamp::text) = hash_change_stamp
                 THEN 1
                 ELSE 0
            END)
    FROM cto.torder_budget
    INNER JOIN temp_update ON temp_update.id = torder_budget.id
```
It is slow, however this:
```
SELECT count(*),
        SUM(CASE WHEN md5(change_stamp::text) = hash_change_stamp
                 THEN 1
                 ELSE 0
            END)
    FROM cto.torder_budget
    INNER JOIN temp_update ON temp_update.id = torder_budget.id
    WHERE torder_budget.id = ANY (array(SELECT id FROM temp_update)) -- This line is new
```
It is fast. So I am working on getting this in envelope.

**Comment by josephtocci** [comment]
Was this fixed? You added a commit but gave nothing further.

**Comment by nunziotocci** [comment]
I just haven't gotten around to upgrading the server that had the issue, so I don't know for sure if it is fixed yet.
