### ISSUE TITLE
New feature: Custom Tag Attribute "Channel=" for listening to data updates.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#27]
Research: github.com/michaellperry/jinaga

I didn't look at jinaga but my understanding is that it gives you the ability to refresh connected clients when the underlying data changes.

A question from the audience at an Envelope presentation asked me if this was possible in Envelope. Of course it is, but since this is likely to be A Big Deal for some people I'm thinking we need to add it as basic functionality to the gs-form, gs-envelope and gs-datasheet objects. The basic idea is to have an attribute something like <gs-form channel="eze.money_table">, then there would be a listener set up on the open web socket to listen for that channel. As channel messages came in, it would refresh the gs-form. 

Not that difficult really. It would be easy for us to make a plan. I'd like it to accept an ID so that only relevant records could refresh. Once done this would be really cool.

**Comment by nunziotocci** [comment]
We have discussed this and we decided that we can't expose a LISTEN API in Envelope for security reasons.
PostgreSQL doesn't restrict LISTEN/NOTIFY so anyone could listen on any channel and possibly get (meta)data about things they don't have permission to.

Instead it is relatively easy to just write an action to listen on a specific channel (with group permissions for the app that uses it) and wait for notifies to come down the WebSocket.
