### ISSUE TITLE
gs-combo requires loading full list

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#3]
When building an application, I've needed to use a combobox to make it easier for the user to find a particular value.

The issue is that the gs-combo element doesn't perform well when it loads a large list (>2000 records with one column, differing text), and in order to autocomplete any value in the list the gs-combo requires that the full list be loaded.

The solution appears to be either
  1) speed up the gs-combo element
or
  2) make it dynamically load a new list as the value changes (loading only values that start with the current value)

**Comment by justintocci** [comment]
Ok, here is the plan.

gs-combo changes:
1) detect the number of records. 
2a) if it's under 2000, then the javascript will be fine. Do the normal thing. 
2b) if it's over 2000, then the javascript should make an ajax call on each keydown. Fetch the list of items beginning with the current set of letters, limit the list to one item. Load the completion from the result.

**Comment by crosstocci** [comment]
Added in next release.
