### ISSUE TITLE
Automatic logout doesn't properly encode redirect link

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#31]
When I am automatically logged out I get brought back to the login screen. The URL shows a `redirect` link in the query string.

Once I log in: if the login page tries to redirect to a URL that has a querystring in it: only the first key of the querystring is used in the link I am redirected to.

This:
```
/index.html?redirect=/env/app/all/file_manager/file_manager.html%3Fsocket%3Dtrue&path%3D%252Fapp%252Fdeveloper_g%252Fgreyspots-1.1.1%252Ftest
```
turns into this:
```
/env/app/all/file_manager/file_manager.html?socket=true
```
but it was supposed to turn into this:
```
/env/app/all/file_manager/file_manager.html?socket=true&path=%2Fapp%2Fdeveloper_g%2Fgreyspots-1.1.1%2Ftest
```
As you can see, the `path` key is missing.

This is because the redirect link doesn't have it's ampersands encoded. What happens is the login page tries to get the redirect key out of the query string, but it runs into an unencoded ampersand and thinks it found the end of the value.

To fix this, find the code that handles setting the redirect link (my guess is that it's in the C) and get that code to encode the ampersands.

**Comment by nunziotocci** [comment]
Fixed in b04868bdbfb007646af556021a82981423cb252a
