### ISSUE TITLE
GS-memo needs the ability to accept tab characters

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#37]
Right now, the gs-memo uses tab to put the focus into the next field. We need to add an attribute to make it so that the tab key adds a tab character.

**Comment by justintocci** [comment]
I would like better editing in a gs-memo. ACE level if possible. Maybe what we have is cool and we need a gs-ace?

**Comment by justintocci** [comment]
Also, the gs-memo causes a save whenever i click. I was doing a little formatting in a gs-memo and every time I clicked to a new line with the mouse the whole record flashed green and it was annoying. I don't know if we want to keep this behaviour and do better in a new element and/or fix it here yet, but this feature is not always desired.

**Comment by crosstocci** [comment]
The gs-memo now has an ```allow-tab-char``` attribute that:
1. prevents the memo from losing focus when you press tab
2. allows tab characters

**Comment by michaeltocci** [comment]
The gs-memo still has the issue where you click to a different point inside the `gs-memo` after adding some characters and it causes a `change` event to be emitted.

With `allow-tab-char` you can add a tab character and click out of the record and it doesn't trigger a `change`. This means that if the last character the user added was a tab and they left the page, it would not be saved.

You need to override the `change` event and emit it yourself in order to make it consistent and fix both of these issues. Here are the behaviors you need to implement:

1) If the `textarea` element emits a `change` event: preventDefault and stopPropagation.
2) When the user puts the `focus` into the textarea, save the textarea's current value as a property of the `gs-memo`.
3) On `focusout`, if there is a difference between the stored value and the current textarea value: trigger a `change` event on the `gs-memo`.

The test file I created is located at `/app/developer_g/greyspots-1.1.1/test/old-datasheet.html`

**Comment by crosstocci** [comment]
Fixed in next release.
