### ISSUE TITLE
Add no-cache to all file responses

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/envelope#42]
I've been having trouble with clients caching files, let's add no-cache to the file responses to circumvent the problem.

**Comment by justintocci** [comment]
what file types are you having trouble with?

**Comment by josephtocci** [comment]
Usually the html documents, but I wouldn't be surprised if javascript and css was also getting cached. This usually happens on iOS Safari. I wouldn't be surprised if the no-store we put on the html files is only ignored by iOS.

**Comment by nunziotocci** [comment]
We aren't using no-store.

**Comment by josephtocci** [comment]
We are in the html meta tags.

**Comment by justintocci** [comment]
Well I don't want to not cache large resources, like our javascript. That would slow down page loads excessively. I'm happy with a refresh of all resources on login I guess.

**Comment by josephtocci** [comment]
The caching issue has to do with the 304 Not Changed responses that was broken. Since we have that figured out and fixed in the last release I am closing this.
