### ISSUE TITLE
gs-text disabled causes text that is too long for field to escape text input.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#44]
![screen shot 2017-03-06 at 2 56 49 pm](https://cloud.githubusercontent.com/assets/14250339/23629357/2402885c-027d-11e7-942e-ea0c75590456.JPG)

please fix. text should not overflow when gs-text is disabled. "readonly" attribute works very well, perhaps you should use that.

**Comment by justintocci** [comment]
gs-text[readonly], input[readonly] {
            opacity: 0.8;
            cursor: default;
            background-color: #D5D5D5;
            color: #444444;
        }

this makes things perfect. Note, there is no pointer blocking. this way I can still copy out of the field, i just can't change it.

**Comment by crosstocci** [comment]
Fixed in next release.
