### ISSUE TITLE
gs-time needs second/millisecond support

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/envelope#47]
I am implementing a gs-timestamp element for issue #35 and I noticed that gs-time only handles hours and minutes.

**Comment by justintocci** [comment]
gs-time is for human input. Usually on human input you only care about minutes since by the time you type the seconds it's not accurate anymore.

**Comment by nunziotocci** [comment]
Fair point, but right now it is stripping seconds. Although, now that you say that, I can't think of any use case for having a user type the seconds. In the cases where you want seconds/milliseconds it would be best to use an action that used `current_timestamp`.
