### ISSUE TITLE
`window.location = 'mailto:...'` causes ajax to fail

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/envelope#49]
If you send an AJAX call, then immediately use `window.location` to open an email, the AJAX is aborted.

**Comment by josephtocci** [comment]
There are two workarounds in this case:
1. `window.open()`, but this leaves a tab open
2. move the `window.location` before the ajax, this works for me because I am using a mailto: link

**Comment by josephtocci** [comment]
@michaeltocci Please take a look at this, if there is nothing to be done then please close the issue.

**Comment by michaeltocci** [comment]
When you want to hit a line without opening tabs or windows, you use a hidden iframe.

The next release will contain a function to handle this for you.

For the time being, here is the code to do this yourself:

```
[YOURELEMENT].addEventListener('click', function () {
    var iframeElement;

    iframeElement = document.createElement('iframe');
    iframeElement.setAttribute('hidden', '');
    iframeElement.addEventListener('load', function () {
        if (iframeElement.parentNode === document.body) {
            document.body.removeChild(iframeElement);
        }
    });

    iframeElement.setAttribute("src", "[YOURMAILTOLINK]");
    document.body.appendChild(iframeElement);
});
```

**Comment by michaeltocci** [comment]
Utility function added.

The next release will contain the new function and it'll be called `GS.hitLink`.
