### ISSUE TITLE
Checkbox type

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/envelope#5]
The checkbox has either true/false or -1/0 depending on what values are already in the checkbox, but when it is null it only uses true/false even if the rest of the table uses -1/0. Please add a type= attribute or similar to choose between boolean style true/false or number style -1/0.

**Comment by michaeltocci** [comment]
This has been fixed. You can now define what type of value the checkbox carries with the attribute `type`.

The `type` attribute can be either "smallint", "boolean" or not set.
```
    If type is "smallint": "-1" for true and "0" for false.
    If type is "boolean": "true" for true and "false" for false.
    If type is not set: the next value will be calculated from the current value.
```
