### ISSUE TITLE
A GS.pushMessage() should appear over a GS.dialog()

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#50]
A GS.pushMessage() should appear over a GS.dialog().

I've got a dialog and a user clicks to delete something and I want to push a message that it is deleted but it's not seen because it appears behind the dialog.

**Comment by michaeltocci** [comment]
To temporarily fix this, put some custom CSS in your page to set the z-index of the `gs-pushmessage-container` to `110`.

**Comment by crosstocci** [comment]
Fixed in next release.
