### ISSUE TITLE
listbox get any column value

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/envelope#55]
Currently we can do
````
document.getElementById('button_pick').value
````
To get the id of the record, but what if I want another column?

Please implement this:
````
document.getElementById('button_pick').column('pn')
````

**Comment by josephtocci** [comment]
Done, will be seen in next release.

**Comment by crosstocci** [comment]
Fix is not backwards-compatible.

For an example try to open a page in the wiki.

**Comment by crosstocci** [comment]
Further investigation revealed that this has to do with someone implementing multi-select
