### ISSUE TITLE
Sort broken

### ISSUE THREAD

**Issue by jentocci** [workflowproducts/envelope#61]
I choose to sort by Ad Account and Posted Date and then hit "Ok":
![screen shot 2017-05-12 at 1 04 22 pm](https://cloud.githubusercontent.com/assets/23283948/26010726/b29ce7ae-3713-11e7-90bc-648c27a1f8b8.png)

The order remains unchanged.
![screen shot 2017-05-12 at 1 08 05 pm](https://cloud.githubusercontent.com/assets/23283948/26010823/18659342-3714-11e7-834a-24b4707a609a.png)

**Comment by josephtocci** [comment]
We had an undefined javascript variable, fixed. Will be seen in next release.
