### ISSUE TITLE
OpenSSL 1.0.1 not supported

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/envelope#62]
I get a linker error on CentOS 7, SSL_CTX_set_alpn_protos is missing.

I will import LibreSSL libssl and try it with OpenSSL 1.0.1

**Comment by josephtocci** [comment]
On mac, I cannot use OpenSSL 0.9.8zg 14 July 2015

**Comment by nunziotocci** [comment]
We've talked about this, and we decided that the LibreSSL TLS API is more trouble than it's worth, so I am going to convert postage/envelope to use the libssl API instead. This will allow us to use OpenSSL or LibreSSL depending on what is installed.

I expect the initial conversion to be done today, but testing other versions and fixing them will take at least two days.

**Comment by justintocci** [comment]
This is so unfortunate. I feel like in a year or two we may be able to switch back to the libtls API but there are just too many problems and they aren't easily resolved.

**Comment by nunziotocci** [comment]
We now support these version of OpenSSL:
- 1.0.1
- 1.0.2
- 1.1.0

*Note: We currently recommend using brew for OpenSSL on macOS*

We also support LibreSSL. Although I haven't tested more than one version, all versions should work.

Next I need to do some `valgrind`ing and create a README for SSL libraries.
I'll close this issue when I'm done.
