### ISSUE TITLE
Project folders

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#65]
Currently, we have a folder structure like this:

```
/app 
    /developer_g (used for bundled developer applications)
/role
/web_root
```

Currently, we expect developers to create a schema and group for each application they wish to create, then add matching folders under /app for the application itself and /role for document control such as user uploaded files.

So for example, an app named "myapp" would get a schema named "myapp" and a group ROLE named "myapp_g", then you'd create folders: 

```
/app/myapp_g (myapp app files)
/role/myapp_g (myapp document control)

```
I propose we scrap this structure and do something more like:

```
/app ( bundled/developer apps )
    /myapp_g  <= could be any group or user name
        / (myapp app files)
        /files (myapp document control)
/web_root
```

I'd like to discuss this further but the advantage here is just having all your application files in one folder structure per application. I suspect we could put more folders here to make the developer's life easy.

Users would then be able to create project folders for public or individual users and it would be obvious how those worked. Under development, an app could be under the developer's name, then to publish it he could just change the top folder name to the group name that needs the app.

If a user has myapp_w then they can upload user_files. If they only have myapp_g then they can only download files.

**Comment by nunziotocci** [comment]
We did the folders the way we did for some good reasons:
- Separation of app and role allows:
    - role to be inside the data directory for .so's to modify
    - role and app to have different file system permissions
    - permission checking to be a little more explicit
- You wouldn't save any folders by doing what you propose

So, I'm going to close this issue for now.
