### ISSUE TITLE
No-cookie Websockets

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/envelope#67]
In our default config file we say:

> \# If the public username and password are set, then no-cookie requests use those credentials. This allows ajax and websockets on specific views and functions for people on the website who have not logged in or don't have a login.
> \# public_username =
> \# public_password =

But we don't actually have no-cookie *websockets*. It would take about 20 minutes to add this. @workflowproducts/dev, do we have a use for this?

**Comment by justintocci** [comment]
Yes! If a developer has a reason for displaying a fair amount of data to a public page then they're going to want to do it efficiently.

**Comment by nunziotocci** [comment]
Ok, I'll get this done. Also, for a NC websocket I need to make ACTION only allowed to run `actionnc_` functions.
