### ISSUE TITLE
gs-timestamp showing PM when AM is correct

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/envelope#68]
Here is the element:
![capture](https://cloud.githubusercontent.com/assets/7560749/26292283/249f360a-3e7a-11e7-8135-f7caabc018cc.PNG)
Here is the data from the network pane of the browser devtools:
![capture2](https://cloud.githubusercontent.com/assets/7560749/26292282/249d5218-3e7a-11e7-949d-760101215e5b.PNG)

I suspect it has nothing to do with gs-timestamp and is instead from the embedded gs-time.

**Comment by josephtocci** [comment]
Fixed, will be seen in next release.
