### ISSUE TITLE
Rename overwrote a file

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/envelope#72]
I renamed
file-old.txt -> file.txt
file.txt -> file.new.txt

and it overwrote the new file with the old one and renamed the old one to .new

Workaround is to do it in two steps until we have fixed this.

**Comment by josephtocci** [comment]
The file I overwrote was my autocomplete rewrite, but backups saved us.

**Comment by nunziotocci** [comment]
Fixed in 735f1c832fcb9d42bf19233ce150f56fa7fda6b7, will be seen in next release.
