### ISSUE TITLE
New datasheet says "undefined" for null values...

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#76]
![screen shot 2017-05-27 at 6 21 41 pm](https://cloud.githubusercontent.com/assets/14250339/26524870/62d64362-4309-11e7-99b9-3c598eefa285.JPG)

Could we get it to say "NULL" instead? Maybe in a grey? If it's easy please do it.

**Comment by crosstocci** [comment]
Fixed in next release.
