### ISSUE TITLE
The JS needs handle login timeouts

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#84]
When a user has been inactive for too long, they are automatically logged out. When this happens, the WebSockets are no longer allowed to connect. So the JS automatically tries to reconnect over and over again.

So, if someone keeps a page open for the whole night, it'll request to reconnect to Envelope roughly 1000 times.

To fix this, if we fail to reconnect 6 times within a reasonable timeframe, the JS should redirect to the login page.

**Comment by nunziotocci** [comment]
Fixed in next release.
