### ISSUE TITLE
How to set the min-width of a column in gs-table?

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#91]
I have labels that are not showing due to the data not being wide enough.

This is causing all kinds of usability problems on tables that have two columns starting with the same letters.

E.g. "Qty Ordered" and "Qty Shipped" both only show "Qty". 

Please either provide a solution or a best practice in the documentation.

**Comment by crosstocci** [comment]
Add a ```style="min-width: ##px"``` attribute on the ```gs-cell``` inside the ```header-record``` template for the columns that are too small.

Quote from the documentation:  ```CSS widths set on these cells using the style attribute will be used as the width of the column.```
