### ISSUE TITLE
Javascript Autocomplete

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/envelope#93]
1:
When i am typing out a tag name, the autocompletes gives me suggestions, if however I simply finishing typing it instead of choosing an option. Like for a `<tr>` the autocomplete stays open. If I press a non-alphanumeric key, I want the autocomplete to close.

2:
Add Vanilla Javascript shortcuts. document.getElementById is usually in the page, but not new pages. Same for xtag shortcuts.

**Comment by crosstocci** [comment]
Javascript snippets have been added in the next release.

**Comment by josephtocci** [comment]
Autocomplete now closes when you type something other than a-z or A-Z.

**Comment by crosstocci** [comment]
Autocomplete should not close if you type a dash, we have lots of tag names that start with ```gs-```.

**Comment by josephtocci** [comment]
Fixed.
