### ISSUE TITLE
GS-Text type=password

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/envelope#94]
When inside a password field with the caps lock on, there should be a caps lock symbol on the right side of the field. It might also be a good idea to have it on non-password fields as well.

**Comment by justintocci** [comment]
this feature should not be default. it should require an attribute. maybe show-caps

**Comment by crosstocci** [comment]
Added in next release. One caveat: if no keys have been pressed when the user focuses the input then it doesn't show the icon until the first key is pressed.
